### ISSUE TITLE
Crash on start v.1.4.1-beta

### ISSUE THREAD

**Issue by infinitel8p** [infinitel8p/Topspot#30]
``` 
09-14 08:57:39.171  8569  9790 I python  : Android kivy bootstrap done. __name__ is __main__
09-14 08:57:39.171  8569  9790 I python  : AND: Ran string
09-14 08:57:39.171  8569  9790 I python  : Run user program, change dir and execute entrypoint
09-14 08:57:39.230  8569  9790 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.ferrara.topspot/files/app/.kivy/logs/kivy_21-09-14_3.txt
09-14 08:57:39.231  8569  9790 I python  : [INFO   ] [Kivy        ] v2.0.0
09-14 08:57:39.231  8569  9790 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.ferrara.topspot/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
09-14 08:57:39.231  8569  9790 I python  : [INFO   ] [Python      ] v3.8.9 (default, Sep 14 2021, 07:23:55)
09-14 08:57:39.231  8569  9790 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
09-14 08:57:39.231  8569  9790 I python  : [INFO   ] [Python      ] Interpreter at ""
09-14 08:57:39.232  8569  9790 I python  : [INFO   ] [KivyMD      ] 1.0.0.dev0 (installed at "./kivymd/__init__.pyc")
09-14 08:57:39.234  8569  9790 I python  : [INFO   ] [Factory     ] 186 symbols loaded
09-14 08:57:39.819  8569  9790 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
09-14 08:57:39.834  8569  9790 I python  : [INFO   ] [Text        ] Provider: sdl2
09-14 08:57:39.835  8569  9790 I python  :  Traceback (most recent call last):
09-14 08:57:39.835  8569  9790 I python  :    File "/home/ludo/topspot/main.py", line 1, in <module>
09-14 08:57:39.835  8569  9790 I python  :    File "/home/ludo/topspot/kivymd/__init__.py", line 70, in <module>
09-14 08:57:39.835  8569  9790 I python  :    File "/home/ludo/topspot/kivymd/font_definitions.py", line 49, in <module>
09-14 08:57:39.836  8569  9790 I python  :    File "/home/ludo/.local/share/python-for-android/build/python-installs/unnamed_dist_4/arm64-v8a/kivy/core/text/__init__.py", line 315, in register
09-14 08:57:39.836  8569  9790 I python  :  OSError: File ./kivymd/fonts/Roboto-Regular.ttf not found
09-14 08:57:39.836  8569  9790 I python  : Python for android ended.
```

**Comment by infinitel8p** [comment]
Deleted KivyMD folder which was previously in the project to have it added through p4a
This may is the cause of the error

- [ ] rebuilding aab with `kivy==2.0.0rc4` and `kivymd==master`
- [ ] deploy on mobile to check for errors
- [ ] push hotfix to playstore

**Comment by infinitel8p** [comment]
6b589fff778d8734400ff5fc1cc6ea5f636e5b00 hotfixed the issue by adding back kivymd folder to project
investigating
